"""
dsr_data_tools: Generic data handling utilities for data splitting and analysis.
"""

from dsr_data_tools.analysis import (
    DataframeColumn,
    DataframeInfo,
    analyze_column_data,
    analyze_dataset,
    generate_interaction_recommendations,
)
from dsr_data_tools.recommendations import (
    RecommendationManager,
    Recommendation,
    NonInformativeRecommendation,
    MissingValuesRecommendation,
    EncodingRecommendation,
    ClassImbalanceRecommendation,
    OutlierDetectionRecommendation,
    OutlierHandlingRecommendation,
    CategoricalConversionRecommendation,
    BooleanClassificationRecommendation,
    BinningRecommendation,
    IntegerConversionRecommendation,
    FloatConversionRecommendation,
    DecimalPrecisionRecommendation,
    ValueReplacementRecommendation,
    FeatureInteractionRecommendation,
    DatetimeConversionRecommendation,
    FeatureExtractionRecommendation,
    DatetimeDurationRecommendation,
    ColumnHint,
    AggregationRecommendation,
)
from dsr_data_tools.enums import (
    RecommendationType,
    EncodingStrategy,
    MissingValueStrategy,
    OutlierStrategy,
    OutlierHandlingStrategy,
    ImbalanceStrategy,
    InteractionType,
    ColumnHintType,
    RoundingMode,
    BitDepth,
)

__all__ = [
    "DataframeColumn",
    "DataframeInfo",
    "analyze_column_data",
    "analyze_dataset",
    "generate_interaction_recommendations",
    "RecommendationManager",
    "Recommendation",
    "NonInformativeRecommendation",
    "MissingValuesRecommendation",
    "EncodingRecommendation",
    "ClassImbalanceRecommendation",
    "OutlierDetectionRecommendation",
    "OutlierHandlingRecommendation",
    "CategoricalConversionRecommendation",
    "BooleanClassificationRecommendation",
    "BinningRecommendation",
    "IntegerConversionRecommendation",
    "FloatConversionRecommendation",
    "DecimalPrecisionRecommendation",
    "ValueReplacementRecommendation",
    "FeatureInteractionRecommendation",
    "DatetimeConversionRecommendation",
    "FeatureExtractionRecommendation",
    "DatetimeDurationRecommendation",
    "ColumnHint",
    "AggregationRecommendation",
    "RecommendationType",
    "EncodingStrategy",
    "MissingValueStrategy",
    "OutlierStrategy",
    "OutlierHandlingStrategy",
    "ImbalanceStrategy",
    "InteractionType",
    "ColumnHintType",
    "RoundingMode",
    "BitDepth",
]

__version__ = "1.1.0"
